"""empty message

Revision ID: bc8fc6a84f03
Revises: ffdc0a98111c
Create Date: 2021-12-04 16:07:01.084708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8fc6a84f03'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('imgsrc', sa.String(), nullable=False),
    sa.Column('set', sa.String(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('artifact_id', sa.Integer(), nullable=True),
    sa.Column('primary_stat', sa.String(), nullable=False),
    sa.Column('primary_stat_value', sa.Integer(), nullable=False),
    sa.Column('secondary_stat_one', sa.String(), nullable=False),
    sa.Column('secondary_stat_one_value', sa.Integer(), nullable=False),
    sa.Column('secondary_stat_two', sa.String(), nullable=False),
    sa.Column('secondary_stat_two_value', sa.Integer(), nullable=False),
    sa.Column('secondary_stat_three', sa.String(), nullable=True),
    sa.Column('secondary_stat_three_value', sa.Integer(), nullable=True),
    sa.Column('secondary_stat_four', sa.String(), nullable=True),
    sa.Column('secondary_stat_four_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
